INSERT INTO barangays VALUES (null, 'Balangobong', '01');
INSERT INTO barangays VALUES (null, 'Bued', '02');
INSERT INTO barangays VALUES (null, 'Bugayong', '03');
INSERT INTO barangays VALUES (null, 'Camangaan', '04');
INSERT INTO barangays VALUES (null, 'Canarvacanan', '05');
INSERT INTO barangays VALUES (null, 'Capas', '06');
INSERT INTO barangays VALUES (null, 'Cili', '07');
INSERT INTO barangays VALUES (null, 'Dumayat', '08');
INSERT INTO barangays VALUES (null, 'Linmansangan', '09');
INSERT INTO barangays VALUES (null, 'Mangcasuy', '010');
INSERT INTO barangays VALUES (null, 'Moreno', '011');
INSERT INTO barangays VALUES (null, 'Pasileng Norte', '012');
INSERT INTO barangays VALUES (null, 'Pasileng Sur', '013');
INSERT INTO barangays VALUES (null, 'Poblacion', '014');
INSERT INTO barangays VALUES (null, 'San Felipe Central', '015');
INSERT INTO barangays VALUES (null, 'San Felipe Sur', '016');
INSERT INTO barangays VALUES (null, 'San Pablo', '017');
INSERT INTO barangays VALUES (null, 'Santa Catalina', '018');
INSERT INTO barangays VALUES (null, 'Santa Maria Norte', '019');
INSERT INTO barangays VALUES (null, 'Santiago', '020');
INSERT INTO barangays VALUES (null, 'Santo Niño', '021');
INSERT INTO barangays VALUES (null, 'Sumabnit', '022');
INSERT INTO barangays VALUES (null, 'Tabuyoc', '023');
INSERT INTO barangays VALUES (null, 'Vacante', '024');
